### ISSUE TITLE
能否提供一份最新的可行性文件包

### ISSUE THREAD

**Issue by zqjilove** [ferventdesert/Hawk#11]
百度网盘的可执行包，貌似好久没更新了。

**Comment by ferventdesert** [comment]
不想编译的话，可执行文件在：

http://download.csdn.net/detail/buptzym/9588196

如果有任何问题，可以加微信：385102891，备注“Hawk”，随后加入【Hawk数据抓取清洗交流】群, 沙漠君第一时间解答你的问题：

**Comment by ferventdesert** [comment]
目前所有最新版， 全部更新在：
https://github.com/ferventdesert/Hawk/releases
