### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by pengyiheng** [ferventdesert/Hawk#14]
Hawk.ETL\Plugins\Transformers\ResponseTF.cs row:51:

**Comment by pengyiheng** [comment]
Hawk.ETL\Plugins\Transformers\ResponseTF.cs  row:51:           
 crawler = processManager.CurrentProcessCollections.FirstOrDefault(d => d.Name == CrawlerSelector) as SmartCrawler;
这里的CrawlerSelector为空导致取不到“网页采集器”对象.
暂时直接赋值 往下了

**Comment by ferventdesert** [comment]
这个问题已经在Hawk 2.0版本中fix
