### ISSUE TITLE
读取文件数据的连接器配置不显示内容

### ISSUE THREAD

**Issue by xwydq** [ferventdesert/Hawk#15]
![20161114101157](https://cloud.githubusercontent.com/assets/5374323/20251375/e1033ab4-aa53-11e6-8805-67e9e9ba4c42.jpg)

**Comment by ferventdesert** [comment]
这个问题， 确实是软件设计不合理的地方。
你可以先切换文件格式， 连接器才会初始化完成。UI里才会呈现相应的选项。
先用这个方案顶一下吧，抱歉抱歉
