### ISSUE TITLE
添加链家二手房网站的总价和单价字段，提取测试显示结果是这样，请问哪里做错了呢？

### ISSUE THREAD

**Issue by Sherrypan1992** [ferventdesert/Hawk#16]
![17 vjsti z3 c _mh _j](https://cloud.githubusercontent.com/assets/23466018/20289324/4191b3b8-ab14-11e6-8b9c-c942ccd58c0f.png)

**Comment by ferventdesert** [comment]
这个问题是，你选取了同一条房产数据的总价和单价，这样树查找算法就不能工作了。
具体的算法参考：
http://www.cnblogs.com/buptzym/p/5454190.html 第三节
hawk 2.0直接使用手气不错，可以跳过添加属性的操作

**Comment by Sherrypan1992** [comment]
好的好的，谢谢沙漠君~~~
