### ISSUE TITLE
视频demo演示的链家数据中，从爬虫转换执行不响应

### ISSUE THREAD

**Issue by shirleymars** [ferventdesert/Hawk#17]
您好： 
     在学习链家demo中，执行从爬虫转换总是不响应？

**Comment by ferventdesert** [comment]
从爬虫转换，实际上是调用网页采集器来实现的，所以就必须知道调用哪一个。
早期版本的hawk，当没有填写“爬虫选择”栏目时，会默认挑选第一个采集器，视频里就是这么处理的。
但这样的问题是会导致引用不明确，因此新版本统一要求输入采集器名称，否则不工作。

结论，填写从爬虫转换->爬虫选择，名字是你要调用的网页采集器的名字

**Comment by ferventdesert** [comment]
从爬虫转换，实际上是调用网页采集器来实现的，所以就必须知道调用哪一个。
早期版本的hawk，当没有填写“爬虫选择”栏目时，会默认挑选第一个采集器，视频里就是这么处理的。
但这样的问题是会导致引用不明确，因此新版本统一要求输入采集器名称，否则不工作。

结论，填写从爬虫转换->爬虫选择，名字是你要调用的网页采集器的名字

**Comment by ferventdesert** [comment]
从爬虫转换，实际上是调用网页采集器来实现的，所以就必须知道调用哪一个。
早期版本的hawk，当没有填写“爬虫选择”栏目时，会默认挑选第一个采集器，视频里就是这么处理的。
但这样的问题是会导致引用不明确，因此新版本统一要求输入采集器名称，否则不工作。

结论，填写从爬虫转换->爬虫选择，名字是你要调用的网页采集器的名字
