### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by ckkbupt** [ferventdesert/Hawk#19]
练习淘女郎爬取时，出现中文乱码，是什么原因呢
![default](https://cloud.githubusercontent.com/assets/18319403/20663484/9d619cfc-b592-11e6-95a9-9f5146ac3bd8.png)

**Comment by ferventdesert** [comment]
这是因为该网页没有带上正确的编码说明，可以在网页采集器，请求详情，编码，选择UTF-8或GBK，然后分别刷新网页试试
