### ISSUE TITLE
a标签中的href的链接如何作为属性提取？

### ISSUE THREAD

**Issue by vsos333** [ferventdesert/Hawk#20]
<a href="/About_H3C/News_Media/News_Media/Company_News/200801/333052_30008_0.htm" title="无线市场群雄逐鹿 H3C等厂商崭露头角——2007年无线网络市场回顾与展望" target="_self">无线市场群雄逐鹿 H3C等厂商崭露头角——2007年无线网络市场回顾与展望</a>

请问一下，类似于这样的a标签，要怎么把href的地址做为一个属性抓出来呢？

**Comment by ferventdesert** [comment]
你看一下这个链接的url值，截取其中的一部分，放到属性检索里去试试。  
另外，很多属性都是在页面中不可见得，需要在html源码中检查。
chrome 右键，检查
ie, firefox, f12开发者工具
