### ISSUE TITLE
大众点评数据采集重复项

### ISSUE THREAD

**Issue by shirleymars** [ferventdesert/Hawk#23]
您好:

学习了大众点评的数据采集视频，但是在最终采集的数据表中，发现极大多数的数据重复项，请问这可能是哪种情况造成的？
多谢

**Comment by ferventdesert** [comment]
请把你的工程文件，发到我的邮箱，或者直接在该问题上贴出来，这个应该是你某一步配置的问题。 Hawk是不负责检查配置合理性的。
