### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by magicdict** [ferventdesert/Hawk#27]
你的MongoDB的驱动太旧了。
推荐使用最新的MongoDB驱动。
我是MongoCola的作者，能不能考虑两个工具的合作呢。
我的想法是你的工作可以作为抓取数据，我的工具作为存储和管理数据。
然后再找个人做机器学习和自然语言处理的工作。

**Comment by ferventdesert** [comment]
挺好的想法，其实我现在就在做机器学习和自然语言处理的工作。 
两个工具确实可以极大地结合起来。如果你想做，我支持你
不过我现在基本转变思路，变成纯代码流。UI对我来说意义不大了。

**Comment by ferventdesert** [comment]
你的工作确实做得非常酷，赞！
