### ISSUE TITLE
反爬怎么破？

### ISSUE THREAD

**Issue by nwuns** [ferventdesert/Hawk#29]
这个是反扒了吧？

-----------------------------------
<body>
	<div class="i_error">
		<img src="./blocked_404.png" alt="404" width="100%">
		<div class="i_logo"><img src="./lagou_logo.png" alt="logo" width="100%"></div>
	</div>	
	<div class="tip">近期我们监控到您所用的IP地址出现异常，您的IP地址是：<span id="ip"></span></div>
	<p class="tip">临时将此IP地址进行安全保护，但可能导致您无法正常登陆。</p>
	<p class="msg">如有问题，请发送邮件至gogo@lagou.com。带来不便，敬请谅解，谢谢！</p>

**Comment by ferventdesert** [comment]
恩，购买代理，在网页采集器-> 请求详情->代理 中设置相关参数。。 如果想让多个网页采集器共用该参数。可以在网页采集器-> 共用采集器名 中填写要共用的采集器的名称。
或者，采用ADSL自动拨号方案
