### ISSUE TITLE
xpath筛选器执行后如何保留原始列？

### ISSUE THREAD

**Issue by pipidoudou** [ferventdesert/Hawk#34]
> 单转多文档的特别说明

> 当你使用List模式的爬虫，或单转多时，虽然生成了多个文档，但原始的数据（如URL）不见了。这是因为Hawk丢弃了这些列。`

> 经过大量实践，如果不这么做，每个新数据后面，都会跟上原始的老数据，如果1转20，则老数据会重复生成20次，这是没有必要的。

> **当然，有时转换时需要包含原始数据的部分列，则可在转换器的新列名中填写要鲤鱼跳龙门的列的名称，中间用空格分割。**

上面这个操作找不到对应的转换，请问要如何处理啊？

**Comment by ferventdesert** [comment]
有不少模块是单转多(UDTF)的， 例如XPath筛选器勾选了“输出多个数据”，就是UDTF，否则就是UDF. 网页采集器在List模式下是UDTF，否则是UDF。  希望能解决你的问题

**Comment by pipidoudou** [comment]
多谢回答，概念我清楚了，现在就是想解决单转多的情况下如何还能保留其他的原始列。
有个实际情况是：网页url是通过ID值拼接的，ID存在数据表中，通过xpath筛选器解析网页获取了多个数据，但ID列没有了，这些值跟ID没有对应关系了。这种情况要如何处理？

**Comment by ferventdesert** [comment]
在转换器的新列名(输出列)中填写要鲤鱼跳龙门的列的名称，中间用空格分割。
不知道是否帮到了你

**Comment by pipidoudou** [comment]
在“转换”的模块里面没有找到“新列名(输出列)”这样的模块，整个数据清洗里面都没有发现……
使用的是https://github.com/ferventdesert/Hawk/releases下载的Hawk 2.0 稳定版

**Comment by ferventdesert** [comment]
哥们我真是无语了，大半夜的我忍不了了开电脑回你
所有的转换器里都有“输出列”，那不是个模块的名字，你自己之前的截图里都会有这三个字。。。
我写的东西那么让人匪夷所思么。。。。。

**Comment by pipidoudou** [comment]
不急不急，要是能举个例子就好理解多了。我的错，抱歉。感谢半夜回复帮助！
