### ISSUE TITLE
最新源码用vs 2015编译后只有“调试信息窗口”，“属性配置器”两个窗口

### ISSUE THREAD

**Issue by yxzyxz** [ferventdesert/Hawk#35]
最新源码用vs 2015编译后只有“调试信息窗口”，“属性配置器”两个窗口，其它窗口都不显示，这是什么问题？

**Comment by yxzyxz** [comment]
最新
![default](https://cloud.githubusercontent.com/assets/659849/22721348/2a2a5a30-edeb-11e6-991e-6a591e792161.png)
源码用vs 2015编译后只有“调试信息窗口”，“属性配置器”两个窗口

**Comment by ferventdesert** [comment]
抱歉现在才回复，这是个插件系统。程序会在启动时动态监测插件，所以如果缺少dll，或者插件配置文件有问题的话，就会出现上面的问题。
你检查一下我发布版本目录下，PluginLoadLogic.xml
