### ISSUE TITLE
大众点评的例子中, 启动并行 page 默认开启时获取到的列表页为 3170个。关闭这个选项，获取到的列表页有6506个。即，启动并行 时，会发生数据丢失的现象。

### ISSUE THREAD

**Issue by paul78li** [ferventdesert/Hawk#37]
大众点评的例子中, 启动并行 page 默认开启时获取到的列表页为 3170个。关闭这个选项，获取到的列表页有6506个。即，启动并行 时，会发生数据丢失的现象。 
我看源码中  SmartETLTool.cs  中，标注了  //TODO:这种分组方式可能会丢数据！！
请问，这个bug现在解决了吗。谢谢！

**Comment by ferventdesert** [comment]
TODO问题已经解决，但是忘了改这个标签了。
主要问题是，并行之后很多请求会同时发起，限制于网速和稳定性原因， 确实会有部分页面丢掉。尤其是当根页面列表页，比如某个类目的根请求没有拿到，则这个类目就丢掉了。
做错误重试目前还是有难度，解决方案就是降低采集速度，提升稳定性
