### ISSUE TITLE
遇到一个网页抓取的是乱码，应该是编码解释不对吧

### ISSUE THREAD

**Issue by jinyangyb** [ferventdesert/Hawk#38]
网址： http://0756fang.com/fang/974914.html
直接打开没有问题，把网页另存，在用hex看，也没有问题
但用hawk的网页采集器抓到的是乱码。
比对后发现是有些字节错了，文件头是 EF BB 3F， 应该没有这么一个头，
etf-8是EF BB BF，把头尝试该为EF BB BF，发现有些字对了，但有些字还是显示不出来，
@ferventdesert 有时间看看是啥原因？

**Comment by ferventdesert** [comment]
厉害，我看到乱码，很少去关心二进制。
你可以调节 网页采集器->请求详情->编码，然后切换一下。。 
Hawk会自动根据html的meta数据，来调节编码，但总会有马失前蹄的时候。比如你这个例子。
手边没有hawk，我回去再检查一下，确实有些网站，不论怎么调节编码都会有乱码。ATA

**Comment by jinyangyb** [comment]
你说的对，把请求编码改为utf8就ok了
我看了一下源码，里面有编码的判断，估计是源码里没有对bom进行判断

**Comment by ferventdesert** [comment]
恩，我之后会加上对BOM头的判断，谢谢你的反馈

**Comment by jinyangyb** [comment]
@ferventdesert 不好意思，还有个问题请教：
1. 还是上面的网址，我怎么提取里面的gps数据？
2. 这个数据要导到哪个应用里，可以直接地图显示
看过你给师姐选房的文章，里面提到可以导到地图并显示，怎么做的？用啥软件？可以分享一下吗？
如果是自己做的软件，不知道是否可以发一份到我邮箱里？谢谢！

**Comment by seifer08ms** [comment]
@jinyangyb ，有经纬度就可以用leaflet等很多地图库可视化，用R或者Python的相关包实现很便捷。

**Comment by jinyangyb** [comment]
@seifer08ms  leaflet是库，我不想写这部分代码，想问问看看是否有现成的工具给我用用，你知道哪个软件有这个功能吗？

**Comment by seifer08ms** [comment]
@jinyangyb GIS软件都可以，比如QGIS，但你需要做一些坐标处理，因为BD-09只能用在百度底图上。

**Comment by jinyangyb** [comment]
@seifer08ms 多谢支援！
