### ISSUE TITLE
没有Main函数？！

### ISSUE THREAD

**Issue by Caizhenyu** [ferventdesert/Hawk#43]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		Program does not contain a static 'Main' method suitable for an entry point	Hawk.Core	E:\Course\Hawk\Hawk-master\Hawk.Core\CSC	
	
启动的是Hawk.Core

**Comment by ferventdesert** [comment]
Hawk的启动位置是Hawk这个工程，入口点非Hawk.Core
