### ISSUE TITLE
请问这套库，c#可以直接使用核心逻辑吗?不要界面

### ISSUE THREAD

**Issue by dhswg20077** [ferventdesert/Hawk#45]
只调用采集的核心功能，界面根据用户需求重新去开发

**Comment by danperor** [comment]
Apache License 2.0 开源协议
自己去看啊，我觉得你要是混github的话，最好先把各个开源协议熟悉一下。使用开源项目的时候直接看作者使用了什么协议。

**Comment by dhswg20077** [comment]
和协议有什么关系？ 我只是问，有不有不带界面的核心库

**Comment by BruceDone** [comment]
界面里面的操作是生成规则的，你要问直接调用的逻辑，你得解决生成规则的问题。

**Comment by dhswg20077** [comment]
规则不能通过代码来配置？
比如linux内核，你的核心是一个东西，GUI只是一个附加的东西，你可以有Centos，Ubuntu，xxxxx。
难道你们的采集逻辑和UI是一体的？

**Comment by BruceDone** [comment]
可以，但是你得知道Hawk的核心就是可视化的生成规则，如果你抛弃了这个特性，改成手写，当然，这也是可行的。

**Comment by ferventdesert** [comment]
我是作者。
Hawk.Core和Hawk.ETL两个包都是不依赖界面的。已经使用MVVM技术完全解耦了。
你去通过code写配置代码，也是可行的。不过非常麻烦就是了，因为hawk原本没打算这么做。
你如果想再度设计UI，甚至设计WEB的page,也是可以的。虽然是Apache，不过你拿去商用了我也并不能把你怎么样，因为这是中国，只是这个活不那么好做，搞之前评估一下

**Comment by dhswg20077** [comment]
谢谢，程序我已经开发完了，只是一个小工具。采集方面没用任何开源库。只是在开始前做了一些调查，并没有找到合适的采集类库。 并且楼上这么傲娇，我也表示用不起 呵呵
