### ISSUE TITLE
“自动嗅探”改成“超级模式”了？

### ISSUE THREAD

**Issue by ZedeX** [ferventdesert/Hawk#46]
文案是不是也要跟着改一下？

图传不上来，就是调试信息窗口“2017-07-09 14:02:53 WARN  在该网页中找不到关键字 xxxxxx,可能是动态请求，可以启用【自动嗅探】,并将浏览器页面翻到包含该关键字的位置 ”

然后右侧3.动态请求嗅探中的文案是“超级模式”

**Comment by ferventdesert** [comment]
了解，我会fix这个问题

**Comment by ferventdesert** [comment]
问题已经修复
