### ISSUE TITLE
可以爬微博数据吗？

### ISSUE THREAD

**Issue by fsheen** [ferventdesert/Hawk#50]
有两个需求，一个是按照搜索关键词和一些条件，爬取相关微博账号，第二个是爬取这些账号的关注数、粉丝数、粉丝列表、注册时间、微博、微博发布时间、等内容，不知道能不能实现啊

**Comment by ferventdesert** [comment]
可以抓一部分，但因为微博现在反爬虫很强，所以没有太大的意义，我有四年前的几千万用户的数据，有需要可以私信我
