### ISSUE TITLE
我想加入一起完善

### ISSUE THREAD

**Issue by liuhongwei** [ferventdesert/Hawk#55]
我用vs2017做的开发，有些地方的bug我想修复，可是我提交后发现本地的标记已经是正常图标。可是我再网站上看不到我推送的代码，哪位指点一下这东西怎么用啊。不会玩呐

**Comment by liuhongwei** [comment]
我看到了，推到我的个人账户下的项目里边了，可以和作者的合并么？

**Comment by liuhongwei** [comment]
我主要是想知道，如果作者更新了，我这边的版本会不会更新。
我这里不会是成了独立版本了吧

**Comment by ferventdesert** [comment]
你好，我是该项目的作者，最近也在更新修复bug，参考其develop分支，你可以提交一个合并请求合并到现在的分支，具体做法可以google一下。另外欢迎给我邮箱联系

**Comment by liuhongwei** [comment]
谢谢
