### ISSUE TITLE
能够自己用Python扩展么？

### ISSUE THREAD

**Issue by LYJ8899** [ferventdesert/Hawk#67]
如果要增加功能，能够自己用python进行扩展么？例如：破解验证码

**Comment by ferventdesert** [comment]
有点困难，Hawk使用的Python是.NET下的ironpython，功能不完备。
有两个方案：
1) 将你的验证码识别包装成http服务，通过hawk调用它
2) 用C#开发hawk插件
3) 试一下ironpython（估计全是坑）
