### ISSUE TITLE
怎么停止开启的任务

### ISSUE THREAD

**Issue by seamusic** [ferventdesert/Hawk#68]
打开你们已有的任务表，然后想测试一下，点了一下启动。结果一直报错，但又找不到可以停止的按钮？启动的按钮还是可以继续点击的。

**Comment by ferventdesert** [comment]
在任务视图中，可以勾选要暂停或取消的任务，然后点击右下角的垃圾桶，即可删除对应的任务。
另外，目前的设计，是允许一个任务同时启动多次的
