### ISSUE TITLE
只有一个属性的时候，点击 属性配置就会报如下错误

### ISSUE THREAD

**Issue by jkingzhu** [ferventdesert/Hawk#71]
只有一个属性的时候，点击 属性配置就会报如下错误“点击按钮: 配置属性  执行失败,错误信息  System.Xml.XPath.XPathException: 表达式的计算结果必须为节点集。”

**Comment by ferventdesert** [comment]
收到，原因是配置属性时，会自动从XPath分析数据，而只有一个属性时就会报错。之后会进行修复
