### ISSUE TITLE
能不能把软件打包编译好发出来呢

### ISSUE THREAD

**Issue by GTMHS** [ferventdesert/Hawk#76]
我用的2013，编译各种错

![image](https://user-images.githubusercontent.com/20610228/40586219-120b03ba-61f2-11e8-9b01-5c41c3532f58.png)

项目 杂项文件 的 NuGet 程序包还原失败: 值不能为 null 或空字符串。
参数名: root。
NuGet 程序包还原失败。
1>------ 已启动全部重新生成:  项目: Hawk.Core, 配置: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1635,5): warning MSB3270: 所生成项目的处理器架构“MSIL”与引用“System.Data.SQLite”的处理器架构“x86”不匹配。这种不匹配可能会导致运行时失败。请考虑通过配置管理器更改您的项目的目标处理器架构，以使您的项目与引用间的处理器架构保持一致，或者为引用关联一个与您的项目的目标处理器架构相符的处理器架构。
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\ConfigFileBase.cs(31,28,31,30): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\ConfigFileBase.cs(31,65,31,66): error CS1519: 类、结构或接口成员声明中的标记“(”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\ConfigFileBase.cs(31,66,31,73): error CS1520: 方法必须具有返回类型
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\ConfigFileBase.cs(31,75,31,76): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\ConfigFileBase.cs(31,81,31,82): error CS1519: 类、结构或接口成员声明中的标记“;”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\ConfigFileBase.cs(42,42,42,44): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\ConfigFileBase.cs(42,45,42,54): error CS1520: 方法必须具有返回类型
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DataCollection.cs(21,38,21,40): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(246,27,246,28): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(249,26,249,27): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(341,29,341,30): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(367,55,367,56): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(368,26,368,27): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(447,30,447,31): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(453,37,453,38): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(464,23,464,24): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(468,23,468,24): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(498,49,498,50): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(502,33,502,34): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\DBConnectorBase.cs(507,37,507,38): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnector.cs(91,27,91,28): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnector.cs(41,42,41,44): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnector.cs(45,46,45,48): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnector.cs(174,39,174,41): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnectorCSV.cs(72,47,72,49): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnectorCSV.cs(74,45,74,47): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnectorExcel.cs(72,40,72,41): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnectorExcel.cs(18,47,18,49): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnectorJson.cs(18,47,18,49): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnectorTable.cs(54,44,54,46): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnectorTable.cs(54,58,54,59): error CS1519: 类、结构或接口成员声明中的标记“;”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnectorTable.cs(56,47,56,49): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnectorTable.cs(243,43,243,45): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileConnectorXML.cs(15,47,15,49): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\FileManager.cs(44,63,44,65): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\MongoDBConnector.cs(137,24,137,25): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\MongoDBConnector.cs(138,20,138,21): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\MySQLConnector.cs(53,49,53,50): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\MySQLConnector.cs(68,37,68,38): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\MySQLConnector.cs(147,21,147,22): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(205,50,205,51): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(206,39,206,40): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(220,48,220,49): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(253,37,253,38): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(263,55,263,56): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(264,23,264,24): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(310,36,310,37): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(439,23,439,24): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(441,23,441,24): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(456,41,456,42): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(479,73,479,74): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\SQLiteConnector.cs(486,33,486,34): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\XPropertyGrid.cs(48,35,48,37): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\XPropertyGrid.cs(48,45,48,46): error CS1519: 类、结构或接口成员声明中的标记“;”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\XPropertyGrid.cs(65,34,65,36): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\XPropertyGrid.cs(65,52,65,53): error CS1519: 类、结构或接口成员声明中的标记“;”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\Vitural\VirtualDataCollection.cs(26,39,26,41): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\Vitural\VirtualDataCollection.cs(26,72,26,73): error CS1519: 类、结构或接口成员声明中的标记“;”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\Vitural\VirtualDataCollection.cs(29,40,29,42): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\Vitural\VirtualDataCollection.cs(32,60,32,62): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\Vitural\VirtualDataCollection.cs(32,88,32,89): error CS1519: 类、结构或接口成员声明中的标记“;”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\Vitural\VirtualDataCollection.cs(35,58,35,60): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Connectors\Vitural\VirtualDataCollection.cs(35,72,35,73): error CS1519: 类、结构或接口成员声明中的标记“;”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\HttpHelper.cs(90,57,90,58): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\HttpHelper.cs(555,40,555,41): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\HttpHelper.cs(559,37,559,38): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\HttpItem.cs(59,31,59,32): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\DebugManager.cs(16,40,16,42): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\DebugManager.cs(18,34,18,36): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\DebugManager.cs(18,52,18,53): error CS1519: 类、结构或接口成员声明中的标记“;”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\DebugManager.cs(20,35,20,37): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(246,35,246,36): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(47,43,47,45): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(47,50,47,63): error CS1520: 方法必须具有返回类型
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(47,64,47,68): error CS1031: 应输入类型
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(49,26,49,27): error CS1519: 类、结构或接口成员声明中的标记“=”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(50,52,50,53): error CS1519: 类、结构或接口成员声明中的标记“(”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(50,60,50,61): error CS1519: 类、结构或接口成员声明中的标记“=”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(53,16,53,24): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(55,16,55,24): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(60,16,60,26): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(63,16,63,22): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(64,17,64,21): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(70,16,70,20): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(77,16,77,20): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(81,52,81,72): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(83,51,83,61): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(135,16,135,20): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(137,43,137,47): error CS1518: 应输入 class、delegate、enum、interface 或 struct
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginManager.cs(145,9,145,10): error CS1022: 应输入类型、命名空间定义或文件尾
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\ExtendMethod.cs(244,44,244,45): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\AbstractPlugIn.cs(34,32,34,34): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\AbstractPlugIn.cs(34,69,34,70): error CS1519: 类、结构或接口成员声明中的标记“(”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\AbstractPlugIn.cs(34,75,34,82): error CS1520: 方法必须具有返回类型
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\AbstractPlugIn.cs(34,84,34,85): error CS1002: 应输入 ;
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\AbstractPlugIn.cs(34,90,34,91): error CS1519: 类、结构或接口成员声明中的标记“;”无效
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\PluginProvider.cs(69,33,69,34): error CS1056: 意外的字符“$”
1>E:\毕设\Hawk-master\Hawk-master\Hawk.Core\Utils\Plugins\XFrmWorkAttribute.cs(18,39,18,41): error CS1002: 应输入 ;
2>------ 已启动全部重新生成:  项目: Hawk.ETL, 配置: Debug Any CPU ------
3>------ 已启动全部重新生成:  项目: Hawk.ETL.Controls, 配置: Debug Any CPU ------
2>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1635,5): warning MSB3245: 未能解析此引用。未能找到程序集“Jint”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。
2>CSC : error CS0006: 未能找到元数据文件“E:\毕设\Hawk-master\Hawk-master\Bin\Hawk.Core.dll”
4>------ 已启动全部重新生成:  项目: HawkScheduler, 配置: Debug Any CPU ------
4>CSC : error CS0006: 未能找到元数据文件“E:\毕设\Hawk-master\Hawk-master\Bin\Hawk.Core.dll”
4>CSC : error CS0006: 未能找到元数据文件“E:\毕设\Hawk-master\Hawk-master\Bin\Hawk.ETL.dll”
3>E:\毕设\Hawk-master\Hawk-master\Hawk.ETL.Controls\DataProcessManagerUI.xaml(17,11): error MC3074: XML 命名空间“clr-namespace:Hawk.Core.Themes;assembly=Hawk.Core”中不存在标记“TaskMetroConverter”。 行 17 位置 11.
3>E:\毕设\Hawk-master\Hawk-master\Hawk.ETL.Controls\AnalyzerUI.xaml(12,4): error MC3074: XML 命名空间“clr-namespace:Hawk.Core.Utils;assembly=Hawk.Core”中不存在标记“GroupConverter”。 行 12 位置 4.
3>E:\毕设\Hawk-master\Hawk-master\Hawk.ETL.Controls\SmartCrawlerUI.xaml(14,10): error MC3074: XML 命名空间“clr-namespace:Hawk.Core.Utils.MVVM;assembly=Hawk.Core”中不存在标记“BindingProxy”。 行 14 位置 10.
3>E:\毕设\Hawk-master\Hawk-master\Hawk.ETL.Controls\SmartETLUI.xaml(21,10): error MC3074: XML 命名空间“clr-namespace:Hawk.Core.Utils;assembly=Hawk.Core”中不存在标记“GeneratorConverter”。 行 21 位置 10.
3>E:\毕设\Hawk-master\Hawk-master\Hawk.ETL.Controls\SubTaskView.xaml(11,10): error MC3074: XML 命名空间“clr-namespace:Hawk.Core.Utils.MVVM;assembly=Hawk.Core”中不存在标记“BindingProxy”。 行 11 位置 10.
3>E:\毕设\Hawk-master\Hawk-master\Hawk.ETL.Controls\SystemStateViewer.xaml(16,10): error MC3074: XML 命名空间“clr-namespace:Hawk.Core.Utils.MVVM;assembly=Hawk.Core”中不存在标记“BindingProxy”。 行 16 位置 10.
3>E:\毕设\Hawk-master\Hawk-master\Hawk.ETL.Controls\TaskManagerView.xaml(7,6): error MC3074: XML 命名空间“clr-namespace:Hawk.Core.Utils.MVVM;assembly=Hawk.Core”中不存在标记“BindingProxy”。 行 7 位置 6.
5>------ 已启动全部重新生成:  项目: Hawk, 配置: Debug Any CPU ------
5>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Fakes\Microsoft.QualityTools.Testing.Fakes.targets(128,5): warning : 无法从引用解析程序集 Jint
5>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1635,5): warning MSB3245: 未能解析此引用。未能找到程序集“Jint”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。
5>CSC : error CS0006: 未能找到元数据文件“E:\毕设\Hawk-master\Hawk-master\Bin\Hawk.Core.dll”
5>CSC : error CS0006: 未能找到元数据文件“E:\毕设\Hawk-master\Hawk-master\Bin\Hawk.ETL.Controls.dll”
5>CSC : error CS0006: 未能找到元数据文件“E:\毕设\Hawk-master\Hawk-master\Bin\Hawk.ETL.dll”
========== 全部重新生成:  成功 0 个，失败 5 个，跳过 0 个 ==========

**Comment by ferventdesert** [comment]
下载地址在主页上如此明显：https://github.com/ferventdesert/Hawk
编译用了C#的一些新特性，在VS2015上编译无误。VS2013应该可以用补丁实现：
