### ISSUE TITLE
链家数据清洗问题

### ISSUE THREAD

**Issue by zhuoranlong** [ferventdesert/Hawk#8]
现在链家北京的网页和视频不一样了，hawk抓取到数据表现为 远洋德邑 | 2室1厅 | 97.64平米 | 东南 | 精装 ，这种情况下需要户型、面积和朝向信息分别成列要怎样写表达式？
谢谢大神分享，还望不吝赐教。。

**Comment by andyweizhou** [comment]
应该是用正则表达式生成几个新列吧

  _____

**Comment by zhuoranlong** [comment]
是的。。可是我不会。。自己上网学了一些正则表达式还是不会写。。> <

**Comment by zhuoranlong** [comment]
求助...虽然好不想做伸手党...= =
