### ISSUE TITLE
那个，微信多少?

### ISSUE THREAD

**Issue by Xinxin19871118** [ferventdesert/Hawk#80]
说个事，希望不要被鄙视。
那个，那个，能出个编译好的exe么？
嗯，微信多少？我，我穷，但是如果可以的话，也是可以的，没别的意思.........

**Comment by SnowmanZhang** [comment]
你是需要一个编译好的版本吗，我记得README中有提供，你仔细看一看

**Comment by ferventdesert** [comment]
参考这个页面：https://github.com/ferventdesert/Hawk/releases
