### ISSUE TITLE
尝试自动重定向的次数太多？

### ISSUE THREAD

**Issue by zhuoranlong** [ferventdesert/Hawk#9]
在网页采集器输入url后刷新的时候出现“尝试自动重定向的次数太多”的错误，要怎么解决？

**Comment by ferventdesert** [comment]
请把url地址发一下，这个问题通常的原因是网页要求重定向，但网页采集器设置的重定向功能关闭了

**Comment by zhuoranlong** [comment]
http://sh.lianjia.com/ershoufang/
谢谢~

**Comment by erinshuian** [comment]
我也是这个问题，怎么开启重定向功能

**Comment by ferventdesert** [comment]
这个问题，最后排查，是因为网页采集器包含的header不被网站接受导致的。  开启重定向本质上也不会解决这个问题。
直白的说，就是被封掉了。
先嗅探更新cookie和header，这个问题就会fix。
