### ISSUE TITLE
用hawk打开大众点评，一直转到输入验证码页面，用其他浏览器打开是正常的

### ISSUE THREAD

**Issue by AvadaX** [ferventdesert/Hawk#90]
我昨天用hawk在大众点评爬了一些数据，今天我用hawk打开大众点评，一直转到输入验证码页面，但是用其他浏览器，比如360或者Chrome等打开大众点评页面是正常的、

请问这个如何解决呢，谢谢~

**Comment by ferventdesert** [comment]
还是头一回遇到这个问题，可能360或chrome设置了代理，所以绕过了验证码页面。 其次是它的详情页和列表页的拦截是不一样的，很可能列表页显示正常，但详情页却被拦截了。
如果想解决的话，可以在hawk中配置代理，或将浏览器中的请求头拷贝到hawk中。 
我遇到的最常见情况，是所有的浏览器都不能访问了 ^_^
