### ISSUE TITLE
数据清洗中，转化为Json的插件，这个要怎么使用

### ISSUE THREAD

**Issue by zenglei286** [ferventdesert/Hawk#96]
感觉最后导出来的就是一个.ToString()的结果,没有达到最后理想的结果

**Comment by ferventdesert** [comment]
可以选择工作模式，另外，如果要想读取内部的信息，还要在之后跟上python转换器，通过脚本提取对应的部分后即可。 参考这个： https://github.com/ferventdesert/Hawk/wiki/4.3-%E8%BD%AC%E6%8D%A2%E5%99%A8#27-json%E8%BD%AC%E6%8D%A2%E5%99%A8
