### ISSUE TITLE
自动化部署部分是否考虑支持 .NET Core

### ISSUE THREAD

**Issue by RockNHawk** [ferventdesert/Hawk#98]
感谢 Hawk，它是爬虫届最良心开源软件！估计也是最强大的开源爬虫程序了。
有两个问题

是否考虑商业化呢？ .NET 届有两个：火车头、VG 浏览器（VG 浏览器可以说非常优雅，和 Hawk 很相似，但是非常强大，强大程度超火车头几条街 ），现在活的都不错。
界面部分 WPF 暂无 .NET Core 无解，生成的自部署爬虫 dll 能否支持  .NET Core 呢？

生成的自部署 dll 或 exe，能够嵌入自己的 .NET 应用程序中，并通过程序调用 API 吗？

**Comment by ferventdesert** [comment]
非常需要，但是目前精力太过有限，非常希望能有人跟我一起完成这件事，如果你感兴趣，可以给我的邮箱留言

**Comment by RockNHawk** [comment]
@ferventdesert 有时间可以参与，不过我目前也是精力太过有限，如果有人有时间做移植工作，我可以提供一些支持，我有大型项目的 .NET Core 移植经验，可以节省移植时间，比如这篇文章可以帮助你
http://www.cnblogs.com/vveiliang/p/7409825.html
将原有的 .NET Framework 工程 csproj 迁移到到 .NET Core 而不必重建，当然还有一些细节没有文章没有提到。

.NET Core 2.1 迁移的代码修改方面工作其实都还好，替换一下依赖的库为 .NET Core 版本，只要没有依赖 MVC，代码的改动并不多。
